### ISSUE TITLE
Pre Capture Lib Pooling - bed validation

### ISSUE THREAD

**Issue by DaWookie1979** [wtsi-clarity/wtsi_clarity#281]
2 - Bed Verification failed! February 13, 2015 - 12:07 pm
[Error ID: 13022015120737] Bed verification has failed: Expected source plate 2460274028854 to be paired with destination plate 2460274385803 at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 41. at /local/scratch01/clarity/bin/../lib/perl5/wtsi_clarity/epp/generic/bed_verifier.pm line 46. at /local/scratch01/clarity/bin/epp line 58.

http://web-claritytest-01.internal.sanger.ac.uk:8080/clarity/work-details/26966

**Comment by jbeast** [comment]
The issue was the naming scheme on the beds. Because this is a (potentially) a "many-to-one" type of transfer the beds need to have a specific naming scheme e.g.

Input Plate 1a -------------
                                      |
Input Plate 1b -------------
                                      |-------------> Output Plate 1
Input Plate 1c -------------
                                      |
Input Plate 1d -------------

Changing this seems to have solved the problem :+1:
